mixed-port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: bb82f2ce-8e0a-4382-bee5-69dee67d2e6a
# docker部署用到的配置
# external-ui: "/opt/clash/ui/clash-dashboard"

dns:
  enable: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - stun.*.*.*
    - stun.*.*
    - miwifi.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - netis.cc
    - router.asus.com
    - repeater.asus.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - tplinkrepeater.net
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.2.4.8
    - 210.2.4.8
    - 223.5.5.5
    - 223.6.6.6
    - 52.80.52.52
    - 117.50.10.10
    - 180.76.76.76
    - 119.28.28.28
    - 119.29.29.29
    - 114.114.114.114
    - 114.114.115.115
    - 101.226.4.6
    - 218.30.118.6
    - 123.125.81.6
    - 140.207.198.6
    - 202.38.64.1
    - 202.112.20.131
    - 202.141.160.95
    - 202.141.160.99
    - 202.141.176.95
    - 202.141.176.99
    - tls://dot.pub:853
    - tls://1.12.12.12:853
    - tls://120.53.53.53:853
    - https://doh.pub/dns-query
    - https://sm2.doh.pub/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://dns.rubyfish.cn/dns-query
  fallback:
    - 9.9.9.9
    - 149.112.112.112
    - 8.8.4.4
    - 8.8.8.8
    - 1.0.0.1
    - 1.1.1.1
    - 208.67.220.220
    - 208.67.220.222
    - 208.67.222.220
    - 208.67.222.222
    - 195.46.39.39
    - 195.46.39.40
    - 168.95.1.1
    - 203.80.96.10
    - 168.95.192.1
    - 164.124.101.2
    - 164.124.107.9
    - 203.248.252.2
    - 203.248.242.2
    - 80.80.80.80
    - 80.80.81.81
    - 199.85.126.10
    - 199.85.127.10
    - 168.126.63.1
    - 168.126.63.2
    - 139.175.252.16
    - 139.175.55.244
    - 202.45.84.58
    - 202.45.84.59
    - 8.26.56.26
    - 23.253.163.53
    - 77.88.8.1
    - 77.88.8.8
    - 89.233.43.71
    - 91.239.100.100
    - 198.101.242.72
    - 8.20.247.20
    - 64.6.64.6
    - 64.6.65.6
    - 209.244.0.3
    - 209.244.0.4
    - 210.220.163.82
    - 219.250.36.130
    - 202.14.67.4
    - 84.200.69.80
    - 84.200.70.40
    - 202.14.67.14
    - 156.154.70.1
    - 156.154.71.1
    - 216.146.35.35
    - 216.146.36.36
    - 77.109.148.136
    - 77.109.148.137
    - 101.101.101.101
    - 101.102.103.104
    - 74.82.42.42
    - 66.220.18.42
    - https://dns.quad9.net/dns-query
    - https://dns9.quad9.net/dns-query
    - tls://dns.google:853
    - https://8.8.4.4/dns-query
    - https://8.8.8.8/dns-query
    - https://dns.google/dns-query
    - tls://1.0.0.1:853
    - tls://1.1.1.1:853
    - tls://one.one.one.one
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.daycat.space/dns-query
    - https://dns.adguard.com/dns-query
    - https://dns-family.adguard.com/dns-query
    - https://dns-unfiltered.adguard.com/dns-query
    - tls://b.iqiq.io:853
    - tls://h.iqiq.io:853
    - tls://j.iqiq.io:853
    - tls://c.passcloud.xyz:853
    - tls://x.passcloud.xyz:853
    - https://a.passcloud.xyz/hk
    - https://a.passcloud.xyz/am
    - https://a.passcloud.xyz/us
    - https://a.passcloud.xyz/sz
    - https://a.passcloud.xyz/cdn
    - https://a.passcloud.xyz/dns-query
    - https://worldwide.passcloud.xyz/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.github.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com

# proxies:

proxy-groups:
  - name: "Auto"
    type: url-test
    use:
      - Airport

  - name: "Proxy"
    type: select
    proxies:
      - Auto
      - China
      - Hong Kong
      - Singapore
      - Japan
      - United States
      - DIRECT

  - name: "China"
    type: select
    use:
      - CN

  - name: "Hong Kong"
    type: select
    use:
      - HK

  - name: "Singapore"
    type: select
    use:
      - SG

  - name: "Japan"
    type: select
    use:
      - JP

  - name: "United States"
    type: select
    use:
      - US

  - name: "Fallback"
    type: fallback
    proxies:
      - Auto
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 1000

proxy-providers:
  Airport:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fra\
      w.githubusercontent.com%2FNiceVPN123%2FNiceVPN%2Fmain%2Flong&insert=false\
      &config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmas\
      ter%2FClash%2Fconfig%2FACL4SSR_Online.ini&filename=Airport.yaml&emoji=tru\
      e&list=true&tfo=false&scv=false&fdn=false&sort=false"
    path: ./Airport.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

  CN:
    type: file
    path: ./Airport.yaml
    filter: "中国|China|CN"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

  HK:
    type: file
    path: ./Airport.yaml
    filter: "香港|Hong Kong|HK"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

  SG:
    type: file
    path: ./Airport.yaml
    filter: "Singapore|新加坡|SG"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

  JP:
    type: file
    path: ./Airport.yaml
    filter: "Japan|日本|JP"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

  US:
    type: file
    path: ./Airport.yaml
    filter: "United States|美国|US"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 86400

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,Proxy
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,Proxy
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
